# Generated by Django 6.1.1 on 2026-10-02 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='qty_gift',
            field=models.PositiveIntegerField(default=0, verbose_name='Sachets offerts'),
        ),
        migrations.AddField(
            model_name='historicaldelivery',
            name='qty_gift',
            field=models.PositiveIntegerField(default=0, verbose_name='Sachets offerts'),
        ),
    ]
